markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "BQ"
markdown: rdiscount

author: "BQ"
atom-baseurl: "https://bchange.github.io/blog"
disqus: "gopherwood"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html

