markdown: rdiscount
highlighter: rouge
permalink: /:year/:month/:day/:title.html
name: "BQ"
markdown: rdiscount

author: "BQ"
atom-baseurl: "https://bchange.github.io/blog"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /blog/index.html
  - title: Tags
    class: fa fa-tags
    href: /blog/tags.html
  - title: About
    class: fa fa-user
    href: /blog/about.html

